version: "2"
run:
  tests: true
linters:
  enable:
    - containedctx
    - copyloopvar
    - depguard
    - errcheck
    - ginkgolinter
    - gocritic
    - govet
    - importas # Enforces consistent import aliases.
    - ineffassign
    - intrange
    - misspell
    - nakedret
    - nolintlint
    - revive
    - staticcheck
    - testifylint
    - thelper
    - unconvert
    - unparam
    - unused
    - usestdlibvars
  settings:
    depguard:
      rules:
        internal:
          files:
            - "**/*.go"
          deny:
            - pkg: github.com/docker/cagent/internal
              desc: don't use /internal/ from /pkg/
    gocritic:
      disabled-checks:
        - dupImport
      enabled-tags:
        - diagnostic
        - style
        - performance
    revive:
      rules:
        - name: exported
          arguments:
            - checkPrivateReceivers
        - name: package-comments
          disabled: false
    staticcheck:
      checks:
        - "-ST1019"
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - errcheck
          - gocyclo
          - gosec
        path: _test\.go
    paths:
      - .*_test\.go$
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 3
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - .*_test\.go$
      - third_party$
      - builtin$
      - examples$
