version: "2"
run:
  tests: true
linters:
  enable:
    - containedctx
    - copyloopvar
    - depguard
    - errcheck
    - ginkgolinter
    - gocritic
    - govet
    - importas # Enforces consistent import aliases.
    - ineffassign
    - intrange
    - misspell
    - nakedret
    - nolintlint
    - revive
    - staticcheck
    - testifylint
    - thelper
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - forbidigo
  settings:
    forbidigo:
      forbid:
        - pattern: context\.Background()
    depguard:
      rules:
        internal:
          files:
            - "**/*.go"
          deny:
            - pkg: github.com/docker/cagent/internal
              desc: don't use /internal/ from /pkg/
        old_yaml:
          files:
            - "**/*.go"
          deny:
            - pkg: gopkg.in/yaml.v3
              desc: don't use deprecated gopkg.in/yaml.v3, use github.com/goccy/go-yaml instead
        testify_is_for_tests:
          files:
            - "**/*.go"
            - "!**/*_test.go"
          deny:
            - pkg: github.com/stretchr/testify
              desc: don't use testify in production code
    gocritic:
      disabled-checks:
        - dupImport
        - hugeParam
        - unnamedResult
        - appendAssign
      enabled-tags:
        - diagnostic
        - style
        - performance
    revive:
      rules:
        - name: exported
          arguments:
            - checkPrivateReceivers
        - name: package-comments
          disabled: false
    staticcheck:
      checks:
        - "-ST1019"
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: _test\.go
        linters:
          - dupl
          - errcheck
          - gocyclo
          - gosec   
      - path-except: _test\.go
        linters:
          - forbidigo
issues:
  max-same-issues: 3
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
  settings:
    gci:
      custom-order: true
      sections:
        - standard
        - default
        - prefix(github.com/docker/cagent)
    gofmt:
      rewrite-rules:
        - pattern: 'interface{}'
          replacement: 'any'
    gofumpt:
      extra-rules: true
