version: "3"

vars:
  DESTDIR: ./bin/build

tasks:
  default:
    cmd: task --list

  dev:
    deps: ["test", "build"]

  build:
    desc: Build the application binary
    cmds:
      - docker buildx bake binaries
    generates:
      - "{{.DESTDIR}}/cagent"

  link:
    desc: Creates a symlink to ~/bin
    cmds:
      - ln -sf {{.USER_WORKING_DIR}}/{{.DESTDIR}}/cagent {{.HOME}}/bin/cagent

  test:
    desc: Run tests
    cmds:
      - go test ./...

  push-agent:
    desc: Build dockerized agent
    internal: true
    vars:
      DOCKER_ID:
        sh: curl -s --unix-socket ~/Library/Containers/com.docker.docker/Data/backend.sock http://_/registry/info | jq -r .id
    deps: ["build"]
    cmds:
      - ./bin/build/cagent build --push ./examples/{{.AGENT}}.yaml {{.DOCKER_ID}}/cagent-{{.AGENT}}

  push-agents:
    desc: Build dockerized agents
    deps:
      - task: push-agent
        vars: { AGENT: 'pirate' }
      - task: push-agent
        vars: { AGENT: 'github' }
      - task: push-agent
        vars: { AGENT: 'gopher' }
      - task: push-agent
        vars: { AGENT: 'mem' }
